
package WSClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws_Sincronizar", targetNamespace = "http://WebService/", wsdlLocation = "http://localhost:8084/GestionAcademica/ws_sincronizar?wsdl")
public class WsSincronizar_Service
    extends Service
{

    private final static URL WSSINCRONIZAR_WSDL_LOCATION;
    private final static WebServiceException WSSINCRONIZAR_EXCEPTION;
    private final static QName WSSINCRONIZAR_QNAME = new QName("http://WebService/", "ws_Sincronizar");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/GestionAcademica/ws_sincronizar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSINCRONIZAR_WSDL_LOCATION = url;
        WSSINCRONIZAR_EXCEPTION = e;
    }

    public WsSincronizar_Service() {
        super(__getWsdlLocation(), WSSINCRONIZAR_QNAME);
    }

    public WsSincronizar_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSINCRONIZAR_QNAME, features);
    }

    public WsSincronizar_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSINCRONIZAR_QNAME);
    }

    public WsSincronizar_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSINCRONIZAR_QNAME, features);
    }

    public WsSincronizar_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSincronizar_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsSincronizar
     */
    @WebEndpoint(name = "ws_sincronizarPort")
    public WsSincronizar getWsSincronizarPort() {
        return super.getPort(new QName("http://WebService/", "ws_sincronizarPort"), WsSincronizar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSincronizar
     */
    @WebEndpoint(name = "ws_sincronizarPort")
    public WsSincronizar getWsSincronizarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebService/", "ws_sincronizarPort"), WsSincronizar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSINCRONIZAR_EXCEPTION!= null) {
            throw WSSINCRONIZAR_EXCEPTION;
        }
        return WSSINCRONIZAR_WSDL_LOCATION;
    }

}
