
package WSClient;

import Utiles.Retorno_MsgObj;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ws_sincronizar", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    Retorno_MsgObj.class
})
public interface WsSincronizar {

    /**
     * 
     * @param cambios
     * @return
     *     returns WSExternalObjects.RetornoMsgObj
     */
    @WebMethod(operationName = "impactar_inconsistencia")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "impactar_inconsistencia", targetNamespace = "http://WebService/", className = "WSClient.ImpactarInconsistencia")
    @ResponseWrapper(localName = "impactar_inconsistenciaResponse", targetNamespace = "http://WebService/", className = "WSClient.ImpactarInconsistenciaResponse")
    @Action(input = "http://WebService/ws_sincronizar/impactar_inconsistenciaRequest", output = "http://WebService/ws_sincronizar/impactar_inconsistenciaResponse")
    public Retorno_MsgObj impactarInconsistencia(
        @WebParam(name = "cambios", targetNamespace = "")
        Retorno_MsgObj cambios);

    /**
     * 
     * @param cambios
     * @return
     *     returns Utiles.Retorno_MsgObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sincronizar", targetNamespace = "http://WebService/", className = "WSClient.Sincronizar")
    @ResponseWrapper(localName = "sincronizarResponse", targetNamespace = "http://WebService/", className = "WSClient.SincronizarResponse")
    @Action(input = "http://WebService/ws_sincronizar/sincronizarRequest", output = "http://WebService/ws_sincronizar/sincronizarResponse")
    public Retorno_MsgObj sincronizar(
        @WebParam(name = "cambios", targetNamespace = "")
        Retorno_MsgObj cambios);

    /**
     * 
     * @param fecha
     * @return
     *     returns Utiles.SincRetorno
     */
    @WebMethod(operationName = "update_fecha")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update_fecha", targetNamespace = "http://WebService/", className = "WSClient.UpdateFecha")
    @ResponseWrapper(localName = "update_fechaResponse", targetNamespace = "http://WebService/", className = "WSClient.UpdateFechaResponse")
    @Action(input = "http://WebService/ws_sincronizar/update_fechaRequest", output = "http://WebService/ws_sincronizar/update_fechaResponse")
    public Retorno_MsgObj updateFecha(
        @WebParam(name = "fecha", targetNamespace = "")
        XMLGregorianCalendar fecha);

}
